### ISSUE TITLE
Add __repr__ for classes

### ISSUE THREAD

**Issue by bsipocz** [astroML/astroML#159]
E.g. for density estimator classes. This would make a more consistent behaviour with scikit-learn. E.g:

```
In [7]: >>> import numpy as np 
   ...: >>> from sklearn.neighbors import KernelDensity 
   ...:  
   ...: >>> np.random.seed(42) 
   ...: >>> X = np.random.normal(size=(1000, 2))  # 1000 points in 2 dims 
   ...: >>> kde = KernelDensity(kernel='gaussian', bandwidth=0.1)  # select the gaussian kernel 
   ...: >>> kde.fit(X)  # fit the model to the data 
   ...: KernelDensity(algorithm='auto', atol=0, bandwidth=0.1, breadth_first=True, 
   ...:        kernel='gaussian', leaf_size=40, metric='euclidean', 
   ...:        metric_params=None, rtol=0) 
```

While

```
In [9]: >>> import numpy as np 
   ...: >>> from astroML.density_estimation import KNeighborsDensity 
   ...:  
   ...: >>> X = np.random.normal(size=(1000, 2))  # 1000 points in 2 dims 
   ...: >>> knd = KNeighborsDensity("bayesian", 10)  # bayesian method, 10 nbrs 
   ...: >>> knd.fit(X)  # fit the model to the data                                                                     
Out[9]: <astroML.density_estimation.density_estimation.KNeighborsDensity at 0x12d38f358>
```

**Comment by bsipocz** [comment]
Alternative could be to check whether it would make sense for us to subclass `sklearn.base.BaseEstimator` for these classes.

**Comment by sashank27** [comment]
@bsipocz I would like to handle this one. So, I should create ``__repr__`` for every estimator?

Besides, I saw that some of the classes (such as `GaussianNB`) extend the `sklearn.base.BaseEstimator`, it would be better to generalize it to all the class. Also, it would handle the definition of the params of a classifier as well.
Otherwise, for every classifier present, and ones to be added in the future, we need to explicitly define ``__repr__``
