### ISSUE TITLE
TypeError: rc() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by blazar716** [astroML/astroML#201]
Hello,

I get the following error message when I try to run 'fig_uniform_mean.py'.  

........./python3.6/site-packages/astroML/plotting/settings.py", line 22, in setup_text_plots
    matplotlib.rc('scatter.edgecolors', 'b')
TypeError: rc() takes 1 positional argument but 2 were given

**Comment by bsipocz** [comment]
This is a bug when using matplotlib >=v3.1. It has been fixed in the developer version, but hasn't yet been released (https://github.com/astroML/astroML/pull/188).

I plan to make a bugfix release next week.

In the meantime you can either wait for the v0.4.1 release, or downgrade matplotlib to be <v3.1, or remove that one line* when you run the example (the figure will be uglier, but everything else should keep working).

* the to remove is: ``setup_text_plots(fontsize=8, usetex=True)``
